/**
 * @fileOverview Type definitions for the Razorpay payment flow.
 *
 * - RazorpayOrderInput - The input type for the payment flow.
 * - RazorpayOrderOutput - The return type for the payment flow.
 */
import { z } from 'zod';

export const RazorpayOrderInputSchema = z.object({
  amount: z.number().describe('The total amount of the transaction in paisa.'),
  merchantTransactionId: z.string().describe('A unique ID for the transaction.'),
});
export type RazorpayOrderInput = z.infer<typeof RazorpayOrderInputSchema>;

export const RazorpayOrderOutputSchema = z.object({
  success: z.boolean(),
  message: z.string(),
  orderId: z.string().optional().describe('The order ID generated by Razorpay.'),
});
export type RazorpayOrderOutput = z.infer<typeof RazorpayOrderOutputSchema>;
